/**
 * Language Profile Service (v2)
 *
 * Manages combined audio + subtitle language profiles. Each movie/series/
 * library can be assigned a profile; the default profile is the single
 * authority in language_settings.default_profile_id (there is no is_default
 * flag on profiles anymore).
 *
 * The status/cutoff matching is v2-native: it iterates the ordered
 * `subtitles` requirements through the shared requirement matcher and only
 * counts a requirement satisfied when a matching row's file exists on disk.
 * `toLegacyPreferences()` remains only as a language-list adapter for the
 * acquisition paths that Task 4 rewires.
 */

import { db } from '$lib/server/db';
import {
	episodes,
	languageProfiles,
	languageSettings,
	libraries,
	movies,
	series,
	smartLists,
	subtitles,
	type LanguageProfileRow
} from '$lib/server/db/schema';
import { eq } from 'drizzle-orm';
import { randomUUID } from 'node:crypto';
import { existsSync } from 'node:fs';
import { extname } from 'node:path';
import { createChildLogger } from '$lib/logging';

const logger = createChildLogger({ logDomain: 'subtitles' as const });
import type { SubtitleStatus } from '../types';
import { normalizeLanguageCode } from '$lib/shared/languages';
import type {
	AudioPreference,
	SubtitleAccessibility,
	SubtitleRequirement
} from '$lib/shared/language-profile.js';
import { DEFAULT_MINIMUM_SCORE, requirementKey } from '$lib/shared/language-profile.js';
import { matchesRequirement } from '../requirement-matcher.js';
import { resolveStoredSubtitlePaths } from '../subtitle-paths.js';
import { LanguageSettingsService } from './LanguageSettingsService.js';
import {
	languageProfileV2CreateSchema,
	languageProfileV2UpdateSchema
} from '$lib/validation/schemas';

/** Language profile with all fields (v2 shape, see $lib/shared/language-profile). */
export type LanguageProfile = LanguageProfileRow;

/** Create profile input */
export type CreateLanguageProfile = Omit<LanguageProfile, 'id' | 'createdAt' | 'updatedAt'>;

/** Update profile input */
export type UpdateLanguageProfile = Partial<
	Omit<LanguageProfile, 'id' | 'createdAt' | 'updatedAt'>
>;

/**
 * Legacy v1 preference entry produced by the status adapter.
 * Temporary until Phase 3 replaces the legacy matcher.
 */
export interface LegacyLanguagePreference {
	code: string;
	forced: boolean;
	hearingImpaired: boolean;
	excludeHi: boolean;
	isCutoff: boolean;
}

/** Legacy matcher view of a v2 profile. */
export interface LegacyProfilePreferences {
	languages: LegacyLanguagePreference[];
	cutoffIndex: number;
}

/** Legacy boolean flags for each v2 accessibility policy ('prefer-hi' degrades to 'any'). */
const ACCESSIBILITY_TO_LEGACY: Record<
	SubtitleAccessibility,
	{ hearingImpaired: boolean; excludeHi: boolean }
> = {
	any: { hearingImpaired: false, excludeHi: false },
	'prefer-hi': { hearingImpaired: false, excludeHi: false },
	'require-hi': { hearingImpaired: true, excludeHi: false },
	'exclude-hi': { hearingImpaired: false, excludeHi: true }
};

/**
 * Map a v2 profile onto the legacy v1 preference list used by the status
 * matcher: tag → code, 'forced' → forced entry, 'both' → regular + forced
 * pair sharing the accessibility flags, 'regular' → regular entry. The legacy
 * cutoff index points at the last entry generated by the cutoff requirement
 * (so a 'both' pair must be fully satisfied before the cutoff fires); a null
 * cutoffRank maps to -1, which disables the legacy cutoff logic.
 */
export function toLegacyPreferences(profile: LanguageProfile): LegacyProfilePreferences {
	const languages: LegacyLanguagePreference[] = [];
	let cutoffIndex = -1;

	profile.subtitles.forEach((requirement, rank) => {
		const flags =
			ACCESSIBILITY_TO_LEGACY[requirement.accessibility] ?? ACCESSIBILITY_TO_LEGACY.any;
		const code = normalizeLanguageCode(requirement.tag);
		const isCutoffRequirement = profile.cutoffRank !== null && rank === profile.cutoffRank;

		if (requirement.variant === 'forced') {
			languages.push({ code, forced: true, ...flags, isCutoff: isCutoffRequirement });
		} else if (requirement.variant === 'both') {
			// Expand into a regular and a forced entry; only the last entry of the
			// pair carries the cutoff so both variants must be satisfied.
			languages.push({ code, forced: false, ...flags, isCutoff: false });
			languages.push({ code, forced: true, ...flags, isCutoff: isCutoffRequirement });
		} else {
			languages.push({ code, forced: false, ...flags, isCutoff: isCutoffRequirement });
		}

		if (isCutoffRequirement) {
			cutoffIndex = languages.length - 1;
		}
	});

	return { languages, cutoffIndex };
}

const VARIANTS = new Set(['regular', 'forced', 'both']);
const ACCESSIBILITIES = new Set(['any', 'prefer-hi', 'require-hi', 'exclude-hi']);

/**
 * Defensively parse the stored audio preference (drizzle usually hands us the
 * parsed object; tolerate raw JSON strings and shape-mismatched data).
 */
export function parseAudioPreference(value: unknown, profileId: string): AudioPreference {
	const parsed = parseJsonColumn(value, 'audio', profileId);
	if (parsed == null || typeof parsed !== 'object' || Array.isArray(parsed)) {
		if (parsed != null) {
			logger.warn({ profileId }, 'Malformed language profile audio JSON; using defaults');
		}
		return { preferOriginal: true, languages: [] };
	}

	const raw = parsed as Partial<AudioPreference>;
	return {
		preferOriginal: typeof raw.preferOriginal === 'boolean' ? raw.preferOriginal : true,
		languages: Array.isArray(raw.languages)
			? raw.languages.filter((tag): tag is string => typeof tag === 'string' && tag.trim() !== '')
			: []
	};
}

/**
 * Defensively parse the stored subtitle requirements, coercing unknown
 * variant/accessibility values and dropping entries without a usable tag.
 */
export function parseSubtitleRequirements(value: unknown, profileId: string): SubtitleRequirement[] {
	const parsed = parseJsonColumn(value, 'subtitles', profileId);
	if (parsed == null) return [];
	if (!Array.isArray(parsed)) {
		logger.warn({ profileId }, 'Malformed language profile subtitles JSON; using defaults');
		return [];
	}

	const requirements: SubtitleRequirement[] = [];
	for (const entry of parsed) {
		if (!entry || typeof entry !== 'object') continue;
		const raw = entry as Record<string, unknown>;
		if (typeof raw.tag !== 'string' || raw.tag.trim() === '') continue;

		requirements.push({
			tag: raw.tag.trim(),
			variant:
				typeof raw.variant === 'string' && VARIANTS.has(raw.variant)
					? (raw.variant as SubtitleRequirement['variant'])
					: 'regular',
			accessibility:
				typeof raw.accessibility === 'string' && ACCESSIBILITIES.has(raw.accessibility)
					? (raw.accessibility as SubtitleRequirement['accessibility'])
					: 'any'
		});
	}
	return requirements;
}

/** Parse a JSON column that may arrive as an unparsed string; undefined on failure. */
function parseJsonColumn(value: unknown, field: string, profileId: string): unknown {
	if (typeof value !== 'string') return value;
	try {
		return JSON.parse(value);
	} catch {
		logger.warn({ profileId, field }, 'Malformed language profile JSON; using defaults');
		return undefined;
	}
}

/**
 * Service for managing language profiles
 */
export class LanguageProfileService {
	private static instance: LanguageProfileService | null = null;

	private constructor() {}

	static getInstance(): LanguageProfileService {
		if (!LanguageProfileService.instance) {
			LanguageProfileService.instance = new LanguageProfileService();
		}
		return LanguageProfileService.instance;
	}

	// =========================================================================
	// Profile CRUD
	// =========================================================================

	/**
	 * Get all language profiles
	 */
	async getProfiles(): Promise<LanguageProfile[]> {
		const rows = await db.select().from(languageProfiles);
		return rows.map((row) => this.rowToProfile(row));
	}

	/**
	 * Get a specific profile by ID
	 */
	async getProfile(id: string): Promise<LanguageProfile | undefined> {
		const rows = await db.select().from(languageProfiles).where(eq(languageProfiles.id, id));
		return rows[0] ? this.rowToProfile(rows[0]) : undefined;
	}

	/**
	 * Get the default profile. The language_settings singleton is the single
	 * default authority (there is no is_default flag on profiles).
	 */
	async getDefaultProfile(): Promise<LanguageProfile | undefined> {
		const defaultProfileId = await LanguageSettingsService.getInstance().getDefaultProfileId();
		if (!defaultProfileId) return undefined;
		return this.getProfile(defaultProfileId);
	}

	/**
	 * Create a new profile
	 */
	async createProfile(profile: CreateLanguageProfile): Promise<LanguageProfile> {
		const parsed = languageProfileV2CreateSchema.parse(profile);

		const id = randomUUID();

		await db.insert(languageProfiles).values({
			id,
			name: parsed.name,
			audio: parsed.audio,
			subtitles: parsed.subtitles,
			cutoffRank: parsed.cutoffRank,
			minimumScore: parsed.minimumScore,
			upgradesAllowed: parsed.upgradesAllowed
		});

		const created = await this.getProfile(id);
		if (!created) {
			throw new Error('Failed to create profile');
		}

		logger.info({ id, name: parsed.name }, 'Created language profile');
		return created;
	}

	/**
	 * Update a profile
	 */
	async updateProfile(id: string, updates: UpdateLanguageProfile): Promise<LanguageProfile> {
		const existing = await this.getProfile(id);
		if (!existing) {
			throw new Error(`Profile not found: ${id}`);
		}

		const parsed = languageProfileV2UpdateSchema.parse(updates ?? {});

		// The update schema is partial, so re-check the cutoff invariant against
		// the merged requirement list.
		const mergedSubtitles = parsed.subtitles ?? existing.subtitles;
		const mergedCutoffRank = parsed.cutoffRank !== undefined ? parsed.cutoffRank : existing.cutoffRank;
		if (mergedCutoffRank !== null && mergedCutoffRank >= mergedSubtitles.length) {
			throw new Error('Cutoff rank must reference a subtitle requirement');
		}

		const updateData: Record<string, unknown> = {
			updatedAt: new Date().toISOString()
		};

		if (parsed.name !== undefined) updateData.name = parsed.name;
		if (parsed.audio !== undefined) updateData.audio = parsed.audio;
		if (parsed.subtitles !== undefined) updateData.subtitles = parsed.subtitles;
		if (parsed.cutoffRank !== undefined) updateData.cutoffRank = parsed.cutoffRank;
		if (parsed.minimumScore !== undefined) updateData.minimumScore = parsed.minimumScore;
		if (parsed.upgradesAllowed !== undefined) updateData.upgradesAllowed = parsed.upgradesAllowed;

		await db.update(languageProfiles).set(updateData).where(eq(languageProfiles.id, id));

		const updated = await this.getProfile(id);
		if (!updated) {
			throw new Error('Failed to update profile');
		}

		logger.info({ id, name: updated.name }, 'Updated language profile');
		return updated;
	}

	/**
	 * Delete a profile and null every reference to it. References are cleared
	 * explicitly because sqlite connections in the app do not enable foreign
	 * keys, so ON DELETE SET NULL cannot be relied upon.
	 */
	async deleteProfile(id: string): Promise<void> {
		const existing = await this.getProfile(id);
		if (!existing) {
			throw new Error(`Profile not found: ${id}`);
		}

		// Remove profile from any media/lists/libraries using it
		await db
			.update(movies)
			.set({ languageProfileId: null })
			.where(eq(movies.languageProfileId, id));
		await db
			.update(series)
			.set({ languageProfileId: null })
			.where(eq(series.languageProfileId, id));
		await db
			.update(smartLists)
			.set({ languageProfileId: null })
			.where(eq(smartLists.languageProfileId, id));
		await db
			.update(libraries)
			.set({ languageProfileId: null })
			.where(eq(libraries.languageProfileId, id));
		await db
			.update(languageSettings)
			.set({ defaultProfileId: null, updatedAt: new Date().toISOString() })
			.where(eq(languageSettings.defaultProfileId, id));

		// Delete the profile
		await db.delete(languageProfiles).where(eq(languageProfiles.id, id));

		logger.info({ id }, 'Deleted language profile');
	}

	// =========================================================================
	// Profile Assignment
	// =========================================================================

	/**
	 * Get profile for a movie (or default)
	 */
	async getProfileForMovie(movieId: string): Promise<LanguageProfile | undefined> {
		const movie = await db.select().from(movies).where(eq(movies.id, movieId)).limit(1);
		if (!movie[0]) return undefined;

		if (movie[0].languageProfileId) {
			return this.getProfile(movie[0].languageProfileId);
		}

		return this.getDefaultProfile();
	}

	/**
	 * Get profile for a series (or default)
	 */
	async getProfileForSeries(seriesId: string): Promise<LanguageProfile | undefined> {
		const show = await db.select().from(series).where(eq(series.id, seriesId)).limit(1);
		if (!show[0]) return undefined;

		if (show[0].languageProfileId) {
			return this.getProfile(show[0].languageProfileId);
		}

		return this.getDefaultProfile();
	}

	/**
	 * Assign a profile to a movie
	 */
	async assignToMovie(movieId: string, profileId: string | null): Promise<void> {
		await db.update(movies).set({ languageProfileId: profileId }).where(eq(movies.id, movieId));
	}

	/**
	 * Assign a profile to a series
	 */
	async assignToSeries(seriesId: string, profileId: string | null): Promise<void> {
		await db.update(series).set({ languageProfileId: profileId }).where(eq(series.id, seriesId));
	}

	/**
	 * Assign a profile to a library (inherited by media added to it)
	 */
	async assignToLibrary(libraryId: string, profileId: string | null): Promise<void> {
		await db
			.update(libraries)
			.set({ languageProfileId: profileId })
			.where(eq(libraries.id, libraryId));
	}

	// =========================================================================
	// Subtitle Status
	// =========================================================================

	/**
	 * Get subtitle status for a movie
	 */
	async getMovieSubtitleStatus(movieId: string): Promise<SubtitleStatus> {
		const profile = await this.getProfileForMovie(movieId);
		if (!profile) {
			return { satisfied: true, missing: [], existing: [] };
		}

		// Get external subtitles
		const existingSubtitles = await db
			.select()
			.from(subtitles)
			.where(eq(subtitles.movieId, movieId));

		return this.calculateStatus(profile, existingSubtitles);
	}

	/**
	 * Get subtitle status for an episode
	 */
	async getEpisodeSubtitleStatus(episodeId: string): Promise<SubtitleStatus> {
		// Get episode and series to find the profile
		const episode = await db.query.episodes.findFirst({
			where: eq(episodes.id, episodeId)
		});

		if (!episode) {
			return { satisfied: true, missing: [], existing: [] };
		}

		const profile = await this.getProfileForSeries(episode.seriesId);
		if (!profile) {
			return { satisfied: true, missing: [], existing: [] };
		}

		// Get external subtitles
		const existingSubtitles = await db
			.select()
			.from(subtitles)
			.where(eq(subtitles.episodeId, episodeId));

		return this.calculateStatus(profile, existingSubtitles);
	}

	/**
	 * Get list of episode IDs missing subtitles for a series
	 */
	async getSeriesEpisodesMissingSubtitles(seriesId: string): Promise<string[]> {
		const profile = await this.getProfileForSeries(seriesId);
		if (!profile) {
			return [];
		}

		// Get all episodes for this series
		const seriesEpisodes = await db.select().from(episodes).where(eq(episodes.seriesId, seriesId));

		const missing: string[] = [];

		for (const episode of seriesEpisodes) {
			const existingSubtitles = await db
				.select()
				.from(subtitles)
				.where(eq(subtitles.episodeId, episode.id));

			const status = await this.calculateStatus(profile, existingSubtitles);
			if (!status.satisfied && status.missing.length > 0) {
				missing.push(episode.id);
			}
		}

		return missing;
	}

	// =========================================================================
	// Helpers
	// =========================================================================

	/**
	 * Calculate subtitle status against a profile.
	 *
	 * A v2 requirement counts as satisfied only when an external subtitle row
	 * matches its full tuple (language, variant, accessibility via the shared
	 * matcher) AND that row's resolved file exists on disk. `exists` is
	 * injectable so tests can simulate the filesystem; each distinct resolved
	 * path is stat'ed at most once per call.
	 *
	 * Cutoff: when `cutoffRank` is set, status is satisfied once the requirement
	 * at that rank is satisfied and `missing` is truncated after it.
	 *
	 * @param profile - The language profile to check against
	 * @param existingSubtitles - External subtitle files from the subtitles table
	 * @param exists - File-existence predicate (defaults to fs.existsSync)
	 */
	private async calculateStatus(
		profile: LanguageProfile,
		existingSubtitles: Array<typeof subtitles.$inferSelect>,
		exists: (path: string) => boolean = existsSync
	): Promise<SubtitleStatus> {
		const external = existingSubtitles.filter((sub) => this.isExternalSubtitleRecord(sub));
		const resolvedPaths = await resolveStoredSubtitlePaths(external);

		// Stat each distinct resolved path once for the whole call.
		const existsByPath = new Map<string, boolean>();
		for (const sub of external) {
			const path = resolvedPaths.get(sub.id) ?? null;
			if (path && !existsByPath.has(path)) {
				existsByPath.set(path, exists(path));
			}
		}

		const requirements = profile.subtitles;
		const satisfiedFlags = requirements.map((requirement) =>
			external.some((sub) => {
				const path = resolvedPaths.get(sub.id) ?? null;
				if (!path || existsByPath.get(path) !== true) return false;
				return matchesRequirement(
					{
						language: sub.language,
						isForced: sub.isForced,
						isHearingImpaired: sub.isHearingImpaired
					},
					requirement
				);
			})
		);

		const cutoffIndex =
			profile.cutoffRank !== null && profile.cutoffRank < requirements.length
				? profile.cutoffRank
				: null;

		// Requirements are ordered by priority; the cutoff truncates the missing
		// list after the cutoff requirement.
		const limit = cutoffIndex === null ? requirements.length : cutoffIndex + 1;
		const missing = requirements.slice(0, limit).filter((_, index) => !satisfiedFlags[index]);
		const satisfied = cutoffIndex === null ? missing.length === 0 : satisfiedFlags[cutoffIndex];

		const existing: SubtitleStatus['existing'] = external.map((sub) => {
			const matched = requirements.find((requirement) =>
				matchesRequirement(
					{
						language: sub.language,
						isForced: sub.isForced,
						isHearingImpaired: sub.isHearingImpaired
					},
					requirement
				)
			);

			return {
				language: normalizeLanguageCode(sub.language),
				subtitleId: sub.id,
				isForced: sub.isForced ?? false,
				isHearingImpaired: sub.isHearingImpaired ?? false,
				matchScore: sub.matchScore ?? undefined,
				requirementKey: matched ? requirementKey(matched) : null
			};
		});

		return { satisfied, missing, existing };
	}

	/**
	 * Convert database row to profile object, defensively parsing the JSON
	 * audio/subtitles columns (fall back to defaults on malformed data).
	 */
	private rowToProfile(row: typeof languageProfiles.$inferSelect): LanguageProfile {
		const audio = parseAudioPreference(row.audio, row.id);
		const requirements = parseSubtitleRequirements(row.subtitles, row.id);

		const cutoffRank =
			typeof row.cutoffRank === 'number' &&
			Number.isInteger(row.cutoffRank) &&
			row.cutoffRank >= 0 &&
			row.cutoffRank < requirements.length
				? row.cutoffRank
				: null;

		return {
			id: row.id,
			name: row.name,
			audio,
			subtitles: requirements,
			cutoffRank,
			minimumScore:
				typeof row.minimumScore === 'number' && row.minimumScore >= 0
					? Math.min(row.minimumScore, 100)
					: DEFAULT_MINIMUM_SCORE,
			upgradesAllowed: row.upgradesAllowed ?? true,
			createdAt: row.createdAt ?? undefined,
			updatedAt: row.updatedAt ?? undefined
		};
	}

	private isExternalSubtitleRecord(subtitle: typeof subtitles.$inferSelect): boolean {
		const format = (subtitle.format ?? '').trim().toLowerCase();
		if (format === 'embedded') {
			return false;
		}

		// Guard against legacy placeholder records that may have been stored with non-file paths.
		const extension = extname(subtitle.relativePath ?? '').toLowerCase();
		const knownExternalExtensions = new Set(['.srt', '.ass', '.ssa', '.sub', '.vtt', '.idx']);
		return knownExternalExtensions.has(extension);
	}
}

/**
 * Get the singleton LanguageProfileService
 */
export function getLanguageProfileService(): LanguageProfileService {
	return LanguageProfileService.getInstance();
}
